name: MuscleDaddies
options:
  bundleIdPrefix: com.muscledaddies
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"

packages:
  FirebaseSDK:
    url: https://github.com/firebase/firebase-ios-sdk
    version: "11.0.0"

targets:
  MuscleDaddies:
    type: application
    platform: iOS
    sources:
      - MuscleDaddies
    resources:
      - MuscleDaddies/Resources/Assets.xcassets
      - MuscleDaddies/Resources/Fonts
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.muscledaddies.app
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_NSHealthShareUsageDescription: "MuscleDaddies reads your workout data to calculate your RPG stats and track your fitness progress."
        INFOPLIST_KEY_NSHealthUpdateUsageDescription: "MuscleDaddies needs write access to sync workout data."
        SWIFT_VERSION: "5.0"
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: true
    info:
      path: MuscleDaddies/Info.plist
      properties:
        UIAppFonts:
          - PressStart2P-Regular.ttf
    entitlements:
      path: MuscleDaddies/MuscleDaddies.entitlements
    dependencies:
      - package: FirebaseSDK
        product: FirebaseAuth
      - package: FirebaseSDK
        product: FirebaseFirestore
      - package: FirebaseSDK
        product: FirebaseMessaging
      - sdk: HealthKit.framework
      - sdk: AuthenticationServices.framework
      - sdk: CryptoKit.framework
  MuscleDaddiesPreview:
    type: application
    platform: iOS
    sources:
      - path: MuscleDaddies
        excludes:
          - App/MuscleDaddiesApp.swift
      - MuscleDaddiesPreview
    resources:
      - MuscleDaddies/Resources/Assets.xcassets
      - MuscleDaddies/Resources/Fonts
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.muscledaddies.preview
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_NSHealthShareUsageDescription: "MuscleDaddies reads your workout data to calculate your RPG stats and track your fitness progress."
        INFOPLIST_KEY_NSHealthUpdateUsageDescription: "MuscleDaddies needs write access to sync workout data."
        SWIFT_VERSION: "5.0"
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: true
    entitlements:
      path: MuscleDaddies/MuscleDaddies.entitlements
    dependencies:
      - package: FirebaseSDK
        product: FirebaseAuth
      - package: FirebaseSDK
        product: FirebaseFirestore
      - package: FirebaseSDK
        product: FirebaseMessaging
      - sdk: HealthKit.framework
      - sdk: AuthenticationServices.framework
      - sdk: CryptoKit.framework
